### PR TITLE
Update imports from gochain-io to gochain and update urfave imports

### PR DESCRIPTION
**Pull request by treeder**
I had conflicts in another program:

```
go: gopkg.in/urfave/cli.v1@v1.21.0: go.mod has non-....v1 module path "github.com/urfave/cli" at revision v1.21.0
go: finding golang.org/x/oauth2 latest
go get: error loading module requirements
```

urfave README says to use the github ones now.

### CODE REVIEW

**Comment by treeder** [comment]
Don't merge yet... doing something else...

**Comment by treeder** [comment]
Lots of files touched, find and replaced all gochain-io's to gochain.

**Comment by jmank88** [comment]
The test failure is due to a set of brittle tests that relied on a std lib error string. I fixed them on the `opencensus` branch, but it's not ready yet, so you could copy them here instead:
https://github.com/gochain/gochain/pull/394/files#diff-4c8792c41515cf193200486a3417b9fc
https://github.com/gochain/gochain/pull/394/files#diff-5ff04ab2d9bb98ddfcb15e7c6a056b59

**Comment by treeder** [comment]
Still seem to fail after copying those tests over.

**Comment by jmank88** [comment]
Looks like it just needs the imports updated, and there may have also been a fluke failure from an unreliable test.

**Comment by treeder** [comment]
Good catch on imports. Fixed and tidied...

**Pull request merged**
