### PR TITLE
Update client.go

### PR DESCRIPTION
**Pull request by m3shine**
if paramsIn == nil , Marshal result is [null] ,result in  too many arguments error when call some methods eg. eth_blockNumber { "params":[]}

### CODE REVIEW

**Comment by jmank88** [comment]
Thanks for the fix!
This change doesn't compile as-is, but we could probably align exactly with geth: https://github.com/ethereum/go-ethereum/blob/172f7778fe498c383e0bdb234aaac4f61d4a2512/rpc/client.go#L455-L464

**Comment by m3shine** [comment]
> Thanks for the fix!
> This change doesn't compile as-is, but we could probably align exactly with geth: https://github.com/ethereum/go-ethereum/blob/172f7778fe498c383e0bdb234aaac4f61d4a2512/rpc/client.go#L455-L464


paramsIn is not necessarily equal to nil.
because len(paramsIn)>=1,even if paramsIn passed by nil.

**Comment by jmank88** [comment]
> paramsIn is not necessarily equal to nil.
> because len(paramsIn)>=1,even if paramsIn passed by nil.

Can you elaborate? I do not think that it would be appropriate to catch a list of nil elements and omit the whole list in that case. It is the caller's responsibility to ensure the elements are set correctly or not included at all.
Perhaps we need some test cases for `newMessage`.

**Comment by m3shine** [comment]
> Can you elaborate? I do not think that it would be appropriate to catch a list of nil elements and omit the whole list in that case. It is the caller's responsibility to ensure the elements are set correctly or not included at all.
> Perhaps we need some test cases for `newMessage`.

I mean the same error will occur if you use the newMessage method of geth: https://github.com/ethereum/go-ethereum/blob/172f7778fe498c383e0bdb234aaac4f61d4a2512/rpc/client.go#L455-L464
let's see:

func (c *Client) newMessage(method string, paramsIn ...interface{}) (*jsonrpcMessage, error) {
	msg := &jsonrpcMessage{Version: vsn, ID: c.nextID(), Method: method}
	if paramsIn != nil { // prevent sending "params":null
		var err error
		if msg.Params, err = json.Marshal(paramsIn); err != nil {
			return nil, err
		}
	}
	return msg, nil
}

3rd line:
if paramsIn != nil { // prevent sending "params":null           here, paramsIn will never equal to nil

even if you call newMessage("eth_blockNumber",nil)，paramsIn will be [nil] not nil，msg.Params will be "null"，so geth will report error  ”too many arguments“

**Comment by jmank88** [comment]
`newMessage("...", nil)` producing `[null]` is not a bug. In this case the caller is explicitly passing a nil value. If the intention is to pass no values, then the caller should omit that nil (`newMessage("...")`), as is done here for `eth_blockNumber`: https://github.com/gochain/gochain/blob/0fe32deca8b2e15517ad595977f2fd0c19e6cd7a/goclient/goclient.go#L77
If producing `null` is still a problem, then we should adopt the geth change to omit the field in that case.

**Comment by m3shine** [comment]
@jmank88 
Thank you for interacting with me. My modifications are just adapted to my situation. It turns out that there are many differences between gochain and native geth.

Is the implementation of the query for transactions different?

**Comment by m3shine** [comment]
> `newMessage("...", nil)` producing `[null]` is not a bug. In this case the caller is explicitly passing a nil value. If the intention is to pass no values, then the caller should omit that nil (`newMessage("...")`), as is done here for `eth_blockNumber`:
> 
> https://github.com/gochain/gochain/blob/0fe32deca8b2e15517ad595977f2fd0c19e6cd7a/goclient/goclient.go#L77
> 
> 
> If producing `null` is still a problem, then we should adopt the geth change to omit the field in that case.

you can try to call：
err := ec.c.CallContext(ctx, &result, "eth_blockNumber")
then , in CallContext：
msg, err := c.newMessage(method, args...)
args is nil no omit
then , in newMessage：
params, err := json.Marshal(paramsIn)
parans is [null]

**Comment by jmank88** [comment]
I am not able to reproduce the problem you are describing. Passing nothing produces `null`, and only explicitly passing a `nil` argument produces `[null]`:
```go
func TestClient_newMessage(t *testing.T) {
	var c Client
	got, err := c.newMessage("none")
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%v", got)
	got, err = c.newMessage("nil", nil)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%v", got)
}
```

```sh
=== RUN   TestClient_newMessage
    TestClient_newMessage: client_test.go:575: {"jsonrpc":"2.0","id":1,"method":"none","params":null}
    TestClient_newMessage: client_test.go:580: {"jsonrpc":"2.0","id":2,"method":"nil","params":[null]}
--- PASS: TestClient_newMessage (0.00s)
PASS

Process finished with exit code 0
```

**Comment by jmank88** [comment]
> It turns out that there are many differences between gochain and native geth.

> Is the implementation of the query for transactions different?

Our code is originally forked from geth, so most differences are in places where geth has changed. We aim to remain as compatible as possible, so we are happy to adapt any non-breaking changes and can even sometimes pull them directly in via a simple `git cherry-pick`. Are you seeing differences in behavior for a specific query?

**Comment by m3shine** [comment]
> I am not able to reproduce the problem you are describing. Passing nothing produces `null`, and only explicitly passing a `nil` argument produces `[null]`:
> 
> ```go
> func TestClient_newMessage(t *testing.T) {
> 	var c Client
> 	got, err := c.newMessage("none")
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> 	t.Logf("%v", got)
> 	got, err = c.newMessage("nil", nil)
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> 	t.Logf("%v", got)
> }
> ```
> 
> ```shell
> === RUN   TestClient_newMessage
>     TestClient_newMessage: client_test.go:575: {"jsonrpc":"2.0","id":1,"method":"none","params":null}
>     TestClient_newMessage: client_test.go:580: {"jsonrpc":"2.0","id":2,"method":"nil","params":[null]}
> --- PASS: TestClient_newMessage (0.00s)
> PASS
> 
> Process finished with exit code 0
> ```

This is the wrong way to test, you ignore the call hierarchy

**Comment by jmank88** [comment]
> This is the wrong way to test, you ignore the call hierarchy

This is a unit test isolating the code you are proposing changing. I would be happy to look at any runnable test code illustrating the problem you are describing, but going up one level in the stack to `(c *Client) CallContext` doesn't affect the input or serialized output.

**Pull request closed without merging**
